### ISSUE TITLE
recyclerview 嵌套时滚动来回会卡

### ISSUE THREAD

**Issue by zhuoshirong** [joker-fu/BannerPager#1]
recyclerview 嵌套时滚动来回会卡，有解决方法吗，请问

**Comment by joker-fu** [comment]
@zhuoshirong 怎么个卡法 demo会卡么

**Comment by zhuoshirong** [comment]
一样，demo也会卡，recyclerview 添加头部，滚动到viewpager不可见时，再滚回来时就会卡，列表卡顿一下，应该是recyclerview回收机制

**Comment by zhuoshirong** [comment]
你可以试一下，我还在找解决方法

**Comment by joker-fu** [comment]
@zhuoshirong 我跑demo没看到卡顿，我测试机是红米2S和三星S7，要不发你联系方式到我邮箱wrap0673@163.com (QQ什么的) 我加你，共同解决下

**Comment by callhh** [comment]
@zhuoshirong 话说我这边一个页面是recyclerview 添加头部，滚动到viewpager不可见时，再滚回来时就viewpager左右滑动会卡一下，第二次滑会没反应，第三次就可以正常滑动了。
然后在滑动到底部的rv列表，在返回到viewpager时滑动又出现类似的问题。

**Comment by callhh** [comment]
@zhuoshirong 我的测试机子是华为P9 我朋友那边手机魅族测说没产生这个问题。。

**Comment by joker-fu** [comment]
@zhuoshirong @callhh 我这边确实没遇到这个问题  找到问题麻烦告知一下 如果说的是轮播要等一会儿才开始 是因为轮播滑动不见的时候停止了轮播 可见了才重新开始轮播 所以会等待你的切换时间 才会切到第二张
